name: Sync Fork with Upstream

# Trigger the workflow on every push or on a schedule
on:
  push:
    branches:
      - web  # Change this to the branch you want to sync
  workflow_dispatch:  # Allows you to manually trigger the workflow

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        persist-credentials: false  # Ensure the GitHub token is not persisted

    # Configure Git with user info for committing
    - name: Set up Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    # Add the upstream repository
    - name: Add upstream repository
      run: |
        git remote add upstream https://github.com/DJLarliboyljudochljus/Mainwebsite.git
        git fetch upstream
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Access the GitHub token for authentication

    # Merge upstream changes into the local repository
    - name: Merge upstream changes
      run: |
        git checkout web  # Ensure you are on the correct branch
         git merge upstream/main --allow-unrelated-histories || true  # Allow unrelated histories

    # Push the changes to your forked repository
    - name: Push changes
      run: |
         git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Grizak/mainwebsite.git web
